POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json


    {"email":"a@gmail.com","password":"amit@#1993"}

###

POST http://localhost:3000/api/user/signup HTTP/1.1
Content-Type: application/json

{
    "email":"rajveer.09.rathod@gmail.com",
    "password":"rajveer@manektech",
    "roleId":"60c0ce922fd38c2458a6e2bb"
}

###
POST http://localhost:3000/api/user/change-password HTTP/1.1
Content-Type: application/json

{
    "old_password": "amit@#1993", "new_password":"abc@#1993"
}

###
POST http://localhost:3000/api/user/add-role HTTP/1.1
Content-Type: application/json

{
    "role": "QA"
}
###
POST http://localhost:3000/api/user/create-designation HTTP/1.1
Content-Type: application/json

{
    "designation": "Designer"
}

###
GET  http://localhost:3000/api/user/getUserTypeList HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/user/create-department HTTP/1.1
Content-Type: application/json

{
    "department": "DOT Net",
    "departmentId": "1002"
}

###
GET  http://localhost:3000/api/user/getDepartmentList HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/employee/create HTTP/1.1
Content-Type: application/json

{
    "role": "QA",
    "roleId":"0005",
    "first_name":"Shubham",
    "middle_name":"",
    "last_name":"Tester",
    "department":"PHP",
    "departmentId":"1001",
    "gender":"asdasd@gmail.com",
    "mobile_number":"12345678",
    "email":"asdasd",
    "status": "Active"
}
###
POST http://localhost:3000/api/user/forgot-password HTTP/1.1
Content-Type: application/json

{
    "email": "rajveer.09.rathod@gmail.com"
}

###
POST http://localhost:3000/api/technology/create HTTP/1.1
Content-Type: application/json

{
    "tech_name": "Angular25"
  
}

###
GET  http://localhost:3000/api/technology/getTechnology HTTP/1.1
Content-Type: application/json

{
    "_id": "60be1d90a2ac210534fbd57b"
}

###
POST   http://localhost:3000/api/technology/updateTechnology/60bdae915b2fc5285c5b3262 HTTP/1.1
Content-Type: application/json

{
    "tech_name": "PHP15"
}





###
POST http://localhost:3000/api/project/create HTTP/1.1
Content-Type: application/json

{
   
    "project_no": 1,
    "project_name": "BTS"
}

###
GET  http://localhost:3000/api/project/getemployee HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/project/gettechnology HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/project/addtechnology HTTP/1.1
Content-Type: application/json

{
    "tech_name": "Ios1"
   
}
###
GET  http://localhost:3000/api/project/getproject/60d46106e3b324379097d19f HTTP/1.1
Content-Type: application/json




###
POST http://localhost:3000/api/project/create HTTP/1.1
Content-Type: application/json

{
   
    "technology_id": "609e72473230742358084d9c",
    "department_id": "609e72473230742358084d9c",
    "employee_id": "609e72473230742358084d9c",
    "project_no": 40,
    "project_name": "BTS11",
    "project_description": "BTS BUG",
    "status": "Running",
    "start_date": "",
    "end_date": ""
}

###
GET http://localhost:3000/api/project/get-project-list HTTP/1.1
Content-Type: application/json


###
# GET https://ded3138.inmotionhosting.com:7778/api/project/gettechnology HTTP/1.1
GET http://ded3138.inmotionhosting.com:8024/api/project/gettechnology
Content-Type: application/json

###
POST http://localhost:3000/api/project/status/add HTTP/1.1
Content-Type: application/json

{
    "value": "Cancelled"
}

###
GET http://localhost:3000/api/project/status HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3000/api/user/gender/add HTTP/1.1
Content-Type: application/json

{
    "value": "Others"
}

###
GET http://localhost:3000/api/user/gender HTTP/1.1


###
GET  http://localhost:3000/api/bugs/getbugstatus HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/bugs/getbugspriority HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/bugs/getbugspriority HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/bugs/getbugstype HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/bugs/getproject HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/bugs/get-bugs-list HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/bugs/getbugdetails/60d5a6a574b2792ef43c5789 HTTP/1.1
Content-Type: application/json



###
POST http://localhost:3000/api/employee/add-status HTTP/1.1
Content-Type: application/json

{
    "status": "Inactive"
}

###
GET  http://localhost:3000/api/employee/get-status HTTP/1.1
Content-Type: application/json


###
GET  http://localhost:3000/api/dashboard/get-project-count HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3000/api/dashboard/get-active-emp HTTP/1.1
Content-Type: application/json


###
GET  http://localhost:3000/api/bugtype/get-bugType HTTP/1.1
Content-Type: application/json

###
POST   http://localhost:3000/api/bugtype/create HTTP/1.1
Content-Type: application/json

{
    "bug_types": "show stopper"
}

###
GET  http://localhost:3000/api/bugstatus/getbugstatusList HTTP/1.1
Content-Type: application/json


###
GET  http://localhost:3000/api/comments/getComment HTTP/1.1
Content-Type: application/json


###
POST   http://localhost:3000/api/bugs/updatebugStatus HTTP/1.1
Content-Type: application/json